// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package student

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqProfile struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProfile) Reset()         { *m = ReqProfile{} }
func (m *ReqProfile) String() string { return proto.CompactTextString(m) }
func (*ReqProfile) ProtoMessage()    {}
func (*ReqProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_9cc75303fb261cb3, []int{0}
}
func (m *ReqProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProfile.Unmarshal(m, b)
}
func (m *ReqProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProfile.Marshal(b, m, deterministic)
}
func (dst *ReqProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProfile.Merge(dst, src)
}
func (m *ReqProfile) XXX_Size() int {
	return xxx_messageInfo_ReqProfile.Size(m)
}
func (m *ReqProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProfile proto.InternalMessageInfo

func (m *ReqProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResProfile struct {
	StudentName          string     `protobuf:"bytes,1,opt,name=studentName,proto3" json:"studentName,omitempty"`
	Subjects             []*Subject `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	GrandTotal           float32    `protobuf:"fixed32,3,opt,name=grandTotal,proto3" json:"grandTotal,omitempty"`
	GrandTotalMarks      float32    `protobuf:"fixed32,4,opt,name=grandTotalMarks,proto3" json:"grandTotalMarks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResProfile) Reset()         { *m = ResProfile{} }
func (m *ResProfile) String() string { return proto.CompactTextString(m) }
func (*ResProfile) ProtoMessage()    {}
func (*ResProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_9cc75303fb261cb3, []int{1}
}
func (m *ResProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResProfile.Unmarshal(m, b)
}
func (m *ResProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResProfile.Marshal(b, m, deterministic)
}
func (dst *ResProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResProfile.Merge(dst, src)
}
func (m *ResProfile) XXX_Size() int {
	return xxx_messageInfo_ResProfile.Size(m)
}
func (m *ResProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ResProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ResProfile proto.InternalMessageInfo

func (m *ResProfile) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *ResProfile) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *ResProfile) GetGrandTotal() float32 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

func (m *ResProfile) GetGrandTotalMarks() float32 {
	if m != nil {
		return m.GrandTotalMarks
	}
	return 0
}

type Subject struct {
	SubjectName          string   `protobuf:"bytes,1,opt,name=subjectName,proto3" json:"subjectName,omitempty"`
	Total                float32  `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`
	Marks                float32  `protobuf:"fixed32,3,opt,name=marks,proto3" json:"marks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_9cc75303fb261cb3, []int{2}
}
func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (dst *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(dst, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *Subject) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Subject) GetMarks() float32 {
	if m != nil {
		return m.Marks
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqProfile)(nil), "student.ReqProfile")
	proto.RegisterType((*ResProfile)(nil), "student.ResProfile")
	proto.RegisterType((*Subject)(nil), "student.Subject")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentClient is the client API for Student service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentClient interface {
	Profile(ctx context.Context, in *ReqProfile, opts ...grpc.CallOption) (*ResProfile, error)
}

type studentClient struct {
	cc *grpc.ClientConn
}

func NewStudentClient(cc *grpc.ClientConn) StudentClient {
	return &studentClient{cc}
}

func (c *studentClient) Profile(ctx context.Context, in *ReqProfile, opts ...grpc.CallOption) (*ResProfile, error) {
	out := new(ResProfile)
	err := c.cc.Invoke(ctx, "/student.Student/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServer is the server API for Student service.
type StudentServer interface {
	Profile(context.Context, *ReqProfile) (*ResProfile, error)
}

func RegisterStudentServer(s *grpc.Server, srv StudentServer) {
	s.RegisterService(&_Student_serviceDesc, srv)
}

func _Student_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.Student/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).Profile(ctx, req.(*ReqProfile))
	}
	return interceptor(ctx, in, info, handler)
}

var _Student_serviceDesc = grpc.ServiceDesc{
	ServiceName: "student.Student",
	HandlerType: (*StudentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Profile",
			Handler:    _Student_Profile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_student_9cc75303fb261cb3) }

var fileDescriptor_student_9cc75303fb261cb3 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x15, 0x17, 0x08, 0x4c, 0x05, 0x54, 0x03, 0x0b, 0xab, 0xaa, 0x50, 0x94, 0x55, 0x16,
	0xa8, 0x91, 0xca, 0x39, 0x8a, 0x50, 0x8a, 0x04, 0x5b, 0x97, 0x98, 0xc8, 0x90, 0xda, 0x21, 0x76,
	0x2f, 0xc0, 0x15, 0xb8, 0x03, 0x17, 0xe2, 0x0a, 0x1c, 0x04, 0xd5, 0xe3, 0x34, 0xa1, 0xbb, 0xfc,
	0xf7, 0xbf, 0x66, 0x7e, 0xc6, 0x70, 0x6e, 0xdd, 0xb6, 0x94, 0xda, 0xcd, 0x9b, 0xd6, 0x38, 0x83,
	0x71, 0x90, 0xd3, 0x59, 0x65, 0x4c, 0x55, 0xcb, 0x5c, 0x34, 0x2a, 0x17, 0x5a, 0x1b, 0x27, 0x9c,
	0x32, 0xda, 0x52, 0x2c, 0x9d, 0x01, 0x14, 0xf2, 0xe3, 0xa1, 0x35, 0xaf, 0xaa, 0x96, 0x78, 0x01,
	0x4c, 0x95, 0x3c, 0x4a, 0xa2, 0xec, 0xac, 0x60, 0xaa, 0x4c, 0xbf, 0xa3, 0x9d, 0x6d, 0x3b, 0x3b,
	0x81, 0x71, 0x98, 0x7a, 0x2f, 0x36, 0x32, 0xe4, 0x86, 0x08, 0x6f, 0xe1, 0xd4, 0x6e, 0xd7, 0x6f,
	0xf2, 0xc5, 0x59, 0xce, 0x92, 0x51, 0x36, 0x5e, 0x4c, 0xe6, 0x5d, 0xaf, 0x15, 0x19, 0xc5, 0x3e,
	0x81, 0x37, 0x00, 0x55, 0x2b, 0x74, 0xf9, 0x68, 0x9c, 0xa8, 0xf9, 0x28, 0x89, 0x32, 0x56, 0x0c,
	0x08, 0x66, 0x70, 0xd9, 0xab, 0xa5, 0x68, 0xdf, 0x2d, 0x3f, 0xf2, 0xa1, 0x43, 0x9c, 0x3e, 0x41,
	0x1c, 0xc6, 0xfb, 0x92, 0xf4, 0xf9, 0xaf, 0x64, 0x8f, 0xf0, 0x1a, 0x8e, 0x9d, 0xdf, 0xc8, 0xfc,
	0x30, 0x12, 0x3b, 0xba, 0xf1, 0x2b, 0xa8, 0x07, 0x89, 0xc5, 0x33, 0xc4, 0x2b, 0xea, 0x8f, 0x4b,
	0x88, 0xbb, 0x43, 0x5c, 0xed, 0x7f, 0xaa, 0x3f, 0xde, 0x74, 0x08, 0xbb, 0x93, 0xa5, 0xfc, 0xf3,
	0xe7, 0xf7, 0x8b, 0x21, 0x4e, 0xf2, 0x60, 0xe6, 0x0d, 0x39, 0xeb, 0x13, 0xff, 0x00, 0x77, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x15, 0xa1, 0x4b, 0x61, 0xb8, 0x01, 0x00, 0x00,
}
